M48
; DRILL file {KiCad 9.0.3-9.0.3-0~ubuntu24.04.1} date 2025-08-16T17:29:39+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-16T17:29:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-9.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
%
G90
G05
T1
X50.73Y-128.61
X125.7Y-85.08
X136.64Y-131.42
M30
